### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by takanda** [takanda/DjangoAPITest#1]

**Comment by takanda** [comment]
- [ ] Celery
    - [ ] Architecture 
        - [ ] Is it necessary to build another server(Broker)?
        - [ ] Can celery client and worker be processed in the same server?
    - [ ] Implementation
        - [ ] How to work?
        - [ ] Can Json be transferred from client to worker by using argument?
- [ ] Async View
    - [ ] Architecture
        - [ ] Can it be processed in a Apache server?
    - [ ] Implementation
        - [ ] How to work?
- [ ] Batch Process 
    - [ ] Implementation
        - [ ] How to work?
